# 自签名根证书 issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: {{ .Release.Namespace | quote }}
spec:
  selfSigned: {}
---

# 根证书
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tke-ca
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: tke-ca
  commonName: TKE
  isCA: true
  duration: {{ .Values.certificate.caCertDuration }}
  renewBefore: {{ .Values.certificate.caCertRenewBefore }}
  subject:
    organizations:
    - Tencent
  issuerRef:
    name: selfsigned
---

# ca issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: {{ .Release.Namespace | quote }}
spec:
  ca: 
    secretName: tke-ca
---

# admin 证书
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tke-ca-admin
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: tke-ca-admin
  duration: {{ .Values.certificate.adminCertDuration }}
  renewBefore: {{ .Values.certificate.adminCertRenewBefore }}
  subject:
    organizations:
    - system:masters
  commonName: admin
  isCA: false
  usages:
    - client auth
  issuerRef:
    name: ca-issuer
---

# webhook 证书
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tke-ca-webhook
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: tke-ca-webhook
  duration: {{ .Values.certificate.webhookCertDuration }}
  renewBefore: {{ .Values.certificate.webhookCertRenewBefore }}
  subject:
    organizations:
    - Tencent
  commonName: webhook
  isCA: false
  usages:
    - client auth
  issuerRef:
    name: ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tke-auth-server-cert
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: tke-auth-server-secret
  duration: {{ .Values.certificate.serverCertDuration }}
  renewBefore: {{ .Values.certificate.serverCertRenewBefore }}
  subject:
    organizations:
    - Tencent
  commonName: TKE-SERVER
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - tke-auth-api
    - auth-api
    - tke-auth-api.tke.svc
    - tke-gateway
    - tke.anywhere
    - registry.tke.com
    - "*.registry.tke.com"
  {{- with .Values.certificate.dnsNames }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  uris: 
  {{- with .Values.certificate.uris }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  ipAddresses: 
    - 127.0.0.1
  {{- with .Values.certificate.ipAddresses }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  issuerRef:
    name: ca-issuer