kind: Service
apiVersion: v1
metadata:
  name: tke-auth-api
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    tke.prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  type: NodePort
  selector:
    app: tke-auth-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9451
      nodePort: {{ .Values.api.nodePort }}
