apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: target
spec:
  selector:
    matchLabels:
      app: target
  template:
    metadata:
      labels:
        app: target
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      containers:
        - name: target
          image: "ccr.ccs.tencentyun.com/wylenwang/target:v1"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8088
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
---
kind: Service
apiVersion: v1
metadata:
  name: target
spec:
  selector:
    app: target
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: target-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: www.baidu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: target
            port:
              number: 8088