# All of the individual sidecar RBAC roles get bound
# to this account.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: csi-hostpath-provisioner-sa
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-hostpathplugin-health-monitor-controller-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-health-monitor-controller-runner
subjects:
- kind: ServiceAccount
  name: csi-hostpath-provisioner-sa
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-hostpathplugin-provisioner-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-provisioner-runner
subjects:
- kind: ServiceAccount
  name: csi-hostpath-provisioner-sa
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-hostpathplugin-health-monitor-controller-role
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-health-monitor-controller-cfg
subjects:
- kind: ServiceAccount
  name: csi-hostpath-provisioner-sa
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-hostpathplugin-provisioner-role
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-provisioner-cfg
subjects:
- kind: ServiceAccount
  name: csi-hostpath-provisioner-sa
  namespace: {{ .Release.Namespace | quote }}
---

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-hostpathplugin
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
{{ toYaml .Values.selector | indent 4 }}
  template:
    metadata:
      labels:
{{ toYaml .Values.podLabels | indent 8 }}
    spec:
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      serviceAccountName: csi-hostpath-provisioner-sa
      containers:
      - args:
{{ toYaml .Values.hostpathProvisioner.args | indent 10 }}
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: PV_DIR
          value: /var/hpvolumes
        - name: VERSION
          value: latest
        image: "{{ .Values.registry }}/{{ .Values.hostpathProvisioner.image.repository }}:{{ .Values.hostpathProvisioner.image.tag }}"
        imagePullPolicy: "{{ .Values.hostpathProvisioner.image.imagePullPolicy }}"
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 9898
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 3
        name: hostpath-provisioner
        ports:
        - containerPort: 9898
          name: healthz
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data-dir
          name: csi-data-dir
        - mountPath: /var/lib/kubelet/plugins
          mountPropagation: Bidirectional
          name: plugins-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /csi
          name: socket-dir
      - args:
{{ toYaml .Values.csiExternalHealthMonitorController.args | indent 10 }}
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: "{{ .Values.registry }}/{{ .Values.csiExternalHealthMonitorController.image.repository }}:{{ .Values.csiExternalHealthMonitorController.image.tag }}"
        imagePullPolicy: "{{ .Values.csiExternalHealthMonitorController.image.imagePullPolicy }}"
        name: csi-external-health-monitor-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
{{ toYaml .Values.nodeDriverRegistrar.args | indent 10 }}
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: "{{ .Values.registry }}/{{ .Values.nodeDriverRegistrar.image.repository }}:{{ .Values.nodeDriverRegistrar.image.tag }}"
        imagePullPolicy: "{{ .Values.nodeDriverRegistrar.image.imagePullPolicy }}"
        name: node-driver-registrar
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
        - mountPath: /csi-data-dir
          name: csi-data-dir
      - args:
{{ toYaml .Values.livenessProbe.args | indent 10 }}
        image: "{{ .Values.registry }}/{{ .Values.livenessProbe.image.repository }}:{{ .Values.livenessProbe.image.tag }}"
        imagePullPolicy: "{{ .Values.livenessProbe.image.imagePullPolicy }}"
        name: liveness-probe
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
{{ toYaml .Values.csiProvisioner.args | indent 10 }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: "{{ .Values.registry }}/{{ .Values.csiProvisioner.image.repository }}:{{ .Values.csiProvisioner.image.tag }}"
        imagePullPolicy: "{{ .Values.csiProvisioner.image.imagePullPolicy }}"
        name: csi-provisioner
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-hostpath
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
          name: plugins-dir
        - hostPath:
            # 'path' is where PV data is persisted on host.
            # using /tmp is also possible while the PVs will not available after plugin container recreation or host reboot
            path: {{ .Values.nodeHostPath }}
            type: DirectoryOrCreate
          name: csi-data-dir