apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ toYaml .Values.ipamd.labels | indent 4 }}
  name: tke-eni-ipamd
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.ipamd.annotations }}
  annotations:
{{ toYaml .Values.ipamd.annotations | indent 4 }}
  {{- end }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
{{ toYaml .Values.ipamd.selector | indent 4 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      {{- if .Values.ipamd.podAnnotations }}
      annotations:
{{ toYaml .Values.ipamd.podAnnotations | indent 8 }}
      {{- end }}
      labels:
{{ toYaml .Values.ipamd.podLabels | indent 8 }}
    spec:
      affinity:
{{ toYaml .Values.ipamd.affinity | indent 8 }}
      containers:
        - args:
            - --clusterid
            - default
            - master
            - 172.16.240.1:443
            - --static-ip=false
            - --enable-vpc-cni=false
            - --enable-customized-pod-cidr=false
            - --enable-cilium-underlay=false
            - --enable-cilium-overlay=true
            - --enable-gr-route-controller=false
            - --enable-route-eni=false
            - --cluster-cidrs={{ .Values.clusterCIDR }}
            - --exclude-cidrs={{ .Values.serviceCIDR }}
            - --desired-pod-number={{ .Values.ipamd.maxNodePodNum }}
          env:
            - name: TKE_ENI_LOG_LEVEL
              value: DEBUG
            - name: NETWORK_ENVIRONMENT
              value: TENCENT_CLOUD_VPC
          image: "{{ .Values.registry }}/{{ .Values.ipamd.image.repository }}:{{ .Values.ipamd.image.tag }}"
          imagePullPolicy: "{{ .Values.ipamd.image.imagePullPolicy }}"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              host: 127.0.0.1
              path: /health
              port: 61678
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: tke-eni-ipamd
          ports:
            - containerPort: 61678
              hostPort: 61678
              name: health-checker
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              host: 127.0.0.1
              path: /health
              port: 61678
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: {{ .Values.ipamd.resources.limits.cpu }}
              memory: {{ .Values.ipamd.resources.limits.memory }}
            requests:
              cpu: {{ .Values.ipamd.resources.requests.cpu }}
              memory: {{ .Values.ipamd.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /host/var/log
              name: log-dir
            - mountPath: /etc/localtime
              name: tz-config
      dnsPolicy: ClusterFirst
      hostNetwork: true
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tke-eni-ipamd
      serviceAccountName: tke-eni-ipamd
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /var/log
            type: ""
          name: log-dir
        - hostPath:
            path: /etc/localtime
            type: ""
          name: tz-config
