apiVersion: v1
kind: ServiceAccount
metadata:
  name: tke-eni-ipamd
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tke-eni-ipamd
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - nodes
      - nodes/status
    verbs:
      - list
      - watch
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - events
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
  - apiGroups:
      - apps
      - extensions
    resources:
      - statefulsets
      - deployments
    verbs:
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - networking.tke.cloud.tencent.com
    resources:
      - staticipconfigs
      - underlayips
      - nodeeniconfigs
      - vpcipclaims
      - vpcips
      - vpcenis
      - eipclaims
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - cilium.io
    resources:
      - ciliumnodes
      - ciliumnodes/status
      - ciliumnodes/finalizers
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tke-eni-ipamd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tke-eni-ipamd
subjects:
  - kind: ServiceAccount
    name: tke-eni-ipamd
    namespace: {{ .Release.Namespace | quote }}
