global:
  enableKeepalived: false
  registry: &registry ccr.ccs.tencentyun.com

keepalived:
  registry: *registry
  labels:
  annotations:
  selector:
    matchLabels:
      app: keepalived
  podAnnotations:
  podLabels:
    app: keepalived
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  image:
    repository: tdccimages/keepalived
    tag: 2.0.16-r0
    imagePullPolicy: IfNotPresent
  vip: 127.0.0.1
  interface: eth0
  
  kubectl:
    image:
      repository: tdccimages/kubectl
      tag: 1.22.7
      imagePullPolicy: IfNotPresent
