kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
{{ toYaml .Values.api.labels | indent 4 }}
  name: tke-registry-api
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.api.annotations }}
  annotations:
{{ toYaml .Values.api.annotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
{{ toYaml .Values.api.selector | indent 4 }}
  template:
    metadata:
      {{- if .Values.api.podAnnotations }}
      annotations:
{{ toYaml .Values.api.podAnnotations | indent 8 }}
      {{- end }}
      labels:
{{ toYaml .Values.api.podLabels | indent 8 }}
    spec:
      affinity:
{{ toYaml .Values.api.affinity | indent 8 }}
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: "NoSchedule"
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: "NoSchedule"
      containers:
        - name: tke-registry-api
          image: "{{ .Values.registry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: "{{ .Values.api.image.imagePullPolicy }}"
          command:
            - /bin/sh
            - -c
            - >
              ln -s /app/certs/cluster/etcd/ca.crt /app/certs/etcd-ca.crt;
              ln -s /app/certs/cluster/etcd/ca.crt /app/certs/etcd.crt;
              ln -s /app/certs/cluster/etcd/ca.key /app/certs/etcd.key;
              ln -s /app/certs/cluster/front-proxy-ca.crt /app/certs/front-proxy-ca.crt;
              ln -s /app/certs/cert-manager/ca.crt /app/certs/ca.crt;
              ln -s /app/certs/cert-manager/ca.key /app/certs/ca.key;
              ln -s /app/certs/cert-manager/admin.crt /app/certs/admin.crt;
              ln -s /app/certs/cert-manager/admin.key /app/certs/admin.key;
              ln -s /app/certs/cert-manager/server.crt /app/certs/server.crt;
              ln -s /app/certs/cert-manager/server.key /app/certs/server.key;
              ln -s /app/certs/cert-manager/token.csv /app/certs/token.csv;
{{- if .Values.enableAudit }}
              /app/bin/tke-registry-api -C=/app/conf/tke-registry-api.toml --audit-policy-file=/app/conf/audit-policy.yaml --audit-webhook-config-file=/app/conf/audit-api-client-config.yaml;
{{- else -}}
              /app/bin/tke-registry-api -C=/app/conf/tke-registry-api.toml
{{- end }}
          volumeMounts:
            - name: cert-manager-certs
              mountPath: /app/certs/cert-manager
            - name: tke-registry-cluster-secret
              mountPath: /app/certs/cluster
            - name: certs
              mountPath: /app/certs
            - name: tke-registry-api-volume
              mountPath: /app/conf
{{- if .Values.filesystemEnabled }}
            - name: registry-data
              mountPath: /storage
{{- end }}
          ports:
            - containerPort: 9453
          readinessProbe:
            httpGet:
              port: 9453
              path: /healthz/ping
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 9453
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: {{ .Values.api.resources.limits.cpu }}
              memory: {{ .Values.api.resources.limits.memory }}
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
{{- if not .Values.persistence.enabled }}
      nodeName: {{ .Values.nodeName }}
{{- end }}
      volumes:
        - name: tke-registry-api-volume
          configMap:
            name: tke-registry-api
        - name: certs
          emptyDir: {}
        - name: tke-registry-cluster-secret
          hostPath:
            path: {{ .Values.certificate.mountPath }}
            type: Directory
        - name: cert-manager-certs
          projected:
            sources:
              - secret:
                  name: tke-ca
                  items:
                    - key: tls.crt
                      path: ca.crt
                    - key: tls.key
                      path: ca.key
                  optional: false
              - secret:
                  name: tke-registry-server-secret
                  items:
                    - key: tls.crt
                      path: server.crt
                    - key: tls.key
                      path: server.key
                  optional: false
              - secret:
                  name: tke-ca-admin
                  items:
                    - key: tls.crt
                      path: admin.crt
                    - key: tls.key
                      path: admin.key
                  optional: false
              - secret:
                  name: tke-registry-cluster-secret
                  items:
                    - key: token.csv
                      path: token.csv
                  optional: false
{{- if eq .Values.storage "filesystem" }}
        - name: registry-data
  {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvcName }}
  {{- else }}
          hostPath:
            path: /var/lib/tke-registry-api
            type: DirectoryOrCreate
  {{- end }}
{{- end }}
