kind: Service
apiVersion: v1
metadata:
  name: tke-registry-api
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    tke.prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    app: tke-registry-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9453
