kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-registry-chart-hook-check
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  chart-hook-check.sh: |
    #!/bin/bash

    function check_deployment_install {
        check=true
        while [ $check = true ]
        do
        check=false
        if [ $check = false ] && [ $(kubectl get deployment $1 -n $2 2>&1 | grep Error | wc -l) -gt 0 ]; then
            check=true
            echo "waiting $1"
            sleep 1
        fi 
        if [ $check = false ] && [ $(kubectl get deployment $1 -n $2 -o jsonpath="{.spec.replicas}") -ne $(kubectl get deployment $1 -n $2 -o jsonpath="{.status.readyReplicas}") ]; then
            check=true
            echo "waiting $1"
            sleep 1
        fi
        done
    }

    function check_deployment_upgrade {
        check=true
        while [ $check = true ]
        do
        check=false
        if [ $check = false ] && [ $(kubectl get deployment $1 -n $2 2>&1 | grep Error | wc -l) -gt 0 ]; then
            check=true
            echo "waiting $1"
            sleep 1
        fi 
        if [ $check = false ] && [ $(kubectl get deployment $1 -n $2 -o jsonpath="{.spec.replicas}") -ne $(kubectl get deployment $1 -n $2 -o jsonpath="{.status.updatedReplicas}") ]; then
            check=true
            echo "waiting $1"
            sleep 1
        fi
        done
        
    }

    function check_components_cr {
        check=true
        while [ $check = true ]
        do
        check=false
        if [ $check = false ] && [ $(kubectl get $1 -A 2>&1 | grep "error" | wc -l) -gt 0 ]; then
            check=true
            echo "waiting $1"
            sleep 1
        fi
        done
    }

    function check_storage_class {
        check=true
        while [ $check = true ]
        do
        check=false
        if [ $check = false ] && [ $(kubectl get storageclass $1 2>&1 | grep "Error" | wc -l) -gt 0 ]; then
            check=true
            echo "waiting persistence storage class"
            sleep 1
        fi
        done
    }

    CHECK_TYPE=$1
    echo $CHECK_TYPE
    case $CHECK_TYPE in
        registry-pre-install-check)
            check_components_cr client
            check_deployment_install tke-auth-api tke
            check_deployment_install tke-auth-controller tke
            ;;
        registry-post-install-check)
            check_components_cr chartgroups
            check_deployment_install tke-registry-api tke
            check_deployment_install tke-registry-controller tke
            ;;
        registry-post-upgrade-check)
            check_components_cr chartgroups
            check_deployment_upgrade tke-registry-api tke
            check_deployment_upgrade tke-registry-controller tke
            ;;
        registry-pre-install-check-persistence-storage)
            check_storage_class {{ .Values.persistence.storageClassName }}
            ;;
    esac
