registry: ccr.ccs.tencentyun.com
labels:
annotations:
selector:
  matchLabels:
    app: tke-gateway
podAnnotations:
podLabels:
  app: tke-gateway
affinity:
image:
  repository: tdccimages/tke-gateway-amd64
  tag: industry-cloud-1.9
  imagePullPolicy: IfNotPresent
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
registryDomainSuffix: registry.tke.com
# tke集群的租户id，默认default
tenantID: default
# OIDC认证方式的secret，默认自动生成
# oIDCClientSecret: 25EOZex3zmIj5glxvYfDBp79YIM
# 是否开启自签名，默认为true
selfSigned: true
# 第三方cert证书，在selfSigned为false时需要填值
serverCrt:
# 第三方certKey，在selfSigned为false时需要填值
serverKey:
enableAuth: true
enableBusiness: 
enableMonitor: true
enableNotify: true
enableRegistry: true
enableLogagent: true
enableAudit: true
enableApplication: true
enableMesh: 
certificate:
  serverCertDuration: 876000h
  serverCertRenewBefore: 875900h
  mountPath: /etc/kubernetes/pki
  dnsNames:
  uris: 
  ipAddresses:
kubectl:
  image:
    repository: tdccimages/kubectl
    tag: 1.22.7
    imagePullPolicy: IfNotPresent
ingress:
  enabled: true
  # add custom ingress rule, for example:
  #   rules:
  #   - host: "tke-gateway"
  #     http:
  #       paths:
  #         - pathType: Prefix
  #           path: "/"
  #           backend:
  #             service:
  #               name: tke-gateway
  #               port:
  #                 number: 80
  rules: []