kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
{{ toYaml .Values.api.labels | indent 4 }}
  name: tke-platform-api
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.api.annotations }}
  annotations:
{{ toYaml .Values.api.annotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
{{ toYaml .Values.api.selector | indent 4 }}
  template:
    metadata:
      annotations:
        checksum/tke_platform_api_config: {{ include (print $.Template.BasePath "/tke-platform-api-configmap.yaml") . | sha256sum }}
        checksum/provider_config: {{ include (print $.Template.BasePath "/provider-config-configmap.yaml") . | sha256sum }}
        checksum/kubelet_config: {{ include (print $.Template.BasePath "/kubelet-configmap.yaml") . | sha256sum }}
        checksum/kubeadm_config: {{ include (print $.Template.BasePath "/kubeadm-configmap.yaml") . | sha256sum }}
        checksum/csi_operator_config: {{ include (print $.Template.BasePath "/csi-operator-manifests-configmap.yaml") . | sha256sum }}
        checksum/gpu_config: {{ include (print $.Template.BasePath "/gpu-manifests-configmap.yaml") . | sha256sum }}
        checksum/keepalived_config: {{ include (print $.Template.BasePath "/keepalived-manifests-configmap.yaml") . | sha256sum }}
        checksum/metrics_server_config: {{ include (print $.Template.BasePath "/metrics-server-manifests-configmap.yaml") . | sha256sum }}
      {{- if .Values.api.podAnnotations }}
{{ toYaml .Values.api.podAnnotations | indent 8 }}
      {{- end }}
      labels:
{{ toYaml .Values.api.podLabels | indent 8 }}
    spec:
      affinity:
{{ toYaml .Values.api.affinity | indent 8 }}
    {{- if .Values.api.tolerations }}
      tolerations: {{ toYaml .Values.api.tolerations | nindent 8 }}
    {{- end }}
      containers:
        - name: tke-platform-api
          image: "{{ .Values.registry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: "{{ .Values.api.image.imagePullPolicy }}"
          command:
            - /bin/sh
            - -c 
            - >
              ln -s /app/certs/cluster/etcd/ca.crt /app/certs/etcd-ca.crt;
              ln -s /app/certs/cluster/etcd/ca.crt /app/certs/etcd.crt;
              ln -s /app/certs/cluster/etcd/ca.key /app/certs/etcd.key;
              ln -s /app/certs/cluster/front-proxy-ca.crt /app/certs/front-proxy-ca.crt;
              ln -s /app/certs/cert-manager/ca.crt /app/certs/ca.crt;
              ln -s /app/certs/cert-manager/ca.key /app/certs/ca.key;
              ln -s /app/certs/cert-manager/admin.crt /app/certs/admin.crt;
              ln -s /app/certs/cert-manager/admin.key /app/certs/admin.key;
              ln -s /app/certs/cert-manager/server.crt /app/certs/server.crt;
              ln -s /app/certs/cert-manager/server.key /app/certs/server.key;
              ln -s /app/certs/cert-manager/token.csv /app/certs/token.csv;
{{- if .Values.api.enableAudit }}
              /app/bin/tke-platform-api -C=/app/conf/tke-platform-api.toml --audit-policy-file=/app/conf/audit-policy.yaml --audit-webhook-config-file=/app/conf/audit-api-client-config.yaml;
{{- else -}}
              /app/bin/tke-platform-api -C=/app/conf/tke-platform-api.toml;
{{- end }}
          volumeMounts:
            - name: cert-manager-certs
              mountPath: /app/certs/cert-manager
            - name: cluster-certs
              mountPath: /app/certs/cluster
            - name: certs
              mountPath: /app/certs
            - name: tke-platform-api-volume
              mountPath: /app/conf
            - name: provider-volume
              mountPath: /app/provider/baremetal
            - name: provider-config-volume
              mountPath: /app/provider/baremetal/conf/
            - name: kubelet-volume
              mountPath: /app/provider/baremetal/conf/kubelet/
            - name: kubeadm-volume
              mountPath: /app/provider/baremetal/conf/kubeadm/
            - name: gpu-manifests-volume
              mountPath: /app/provider/baremetal/manifests/gpu/
            - name: csi-operator-manifests-volume
              mountPath: /app/provider/baremetal/manifests/csi-operator/
            - name: keepalived-manifests-volume
              mountPath: /app/provider/baremetal/manifests/keepalived/
            - name: metrics-server-manifests-volume
              mountPath: /app/provider/baremetal/manifests/metrics-server/
          ports:
            - containerPort: 9443
          readinessProbe:
            httpGet:
              port: 9443
              path: /healthz/ping
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 9443
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
        {{- if .Values.api.resources }}
          resources: {{ toYaml .Values.api.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: certs
          emptyDir: {}
        - name: cluster-certs
          hostPath:
            path: {{ .Values.certificate.mountPath }}
            type: Directory
        - name: cert-manager-certs
          projected:
            sources:
            - secret:
                name: tke-ca
                items:
                - key: tls.crt
                  path: ca.crt
                - key: tls.key
                  path: ca.key
                optional: false
            - secret:
                name: tke-platform-server-secret
                items:
                - key: tls.crt
                  path: server.crt
                - key: tls.key
                  path: server.key
                optional: false
            - secret:
                name: tke-ca-admin
                items:
                - key: tls.crt
                  path: admin.crt
                - key: tls.key
                  path: admin.key
                optional: false
            - secret:
                name: tke-platform-cluster-secrets
                items:
                - key: token.csv
                  path: token.csv
                optional: false
        - name: tke-platform-api-volume
          configMap:
            name: tke-platform-api
        - name: provider-volume
          emptyDir: {}
        - name: provider-config-volume
          configMap:
            name: provider-config
        - name: kubelet-volume
          configMap:
            name: kubelet
        - name: kubeadm-volume
          configMap:
            name: kubeadm
        - name: gpu-manifests-volume
          configMap:
            name: gpu-manifests
        - name: csi-operator-manifests-volume
          configMap:
            name: csi-operator-manifests
        - name: keepalived-manifests-volume
          configMap:
            name: keepalived-manifests
        - name: metrics-server-manifests-volume
          configMap:
            name: metrics-server-manifests
