apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tke-monitor-server-cert
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: tke-monitor-server-secret
  duration: {{ .Values.certificate.serverCertDuration }}
  renewBefore: {{ .Values.certificate.serverCertRenewBefore }}
  subject:
    organizations:
    - Tencent
  commonName: TKE-SERVER
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - tke-monitor-api
    - monitor-api
    - tke-monitor-api.tke.svc
  {{- with .Values.certificate.dnsNames }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  uris: 
  {{- with .Values.certificate.uris }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  ipAddresses: 
    - 127.0.0.1
  {{- with .Values.certificate.ipAddresses }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  issuerRef:
    name: ca-issuer