kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-application-controller
  namespace: tke
data:
  tke-application-controller.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.platform]
      api_server = "https://tke-platform-api"
      api_server_client_config = "/app/conf/tke-platform-config.yaml"

      [client.application]
      api_server = "https://tke-application-api"
      api_server_client_config = "/app/conf/tke-application-config.yaml"

    [features]
      [features.repo]
        scheme = "https"
        domain_suffix = "{{ .Values.registryDomainSuffix }}"
        admin = "{{ .Values.registryAdminUsername }}"
        admin_password = "{{ .Values.registryAdminPassword }}"
        cafile = "/app/certs/ca.crt"

  tke-platform-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-platform-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke

  tke-application-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-application-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke

