kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
{{ toYaml .Values.api.labels | indent 4 }}
  name: tke-application-api
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
{{ toYaml .Values.api.selector | indent 4 }}
  template:
    metadata:
      labels:
{{ toYaml .Values.api.podLabels | indent 8 }}
    spec:
      affinity:
{{ toYaml .Values.api.affinity | indent 8 }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: "NoSchedule"
      containers:
        - name: tke-application-api
          image: {{ .Values.registry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - >
              ln -s /app/certs/cluster/etcd/ca.crt /app/certs/etcd-ca.crt;
              ln -s /app/certs/cluster/etcd/ca.crt /app/certs/etcd.crt;
              ln -s /app/certs/cluster/etcd/ca.key /app/certs/etcd.key;
              ln -s /app/certs/cluster/front-proxy-ca.crt /app/certs/front-proxy-ca.crt;
              ln -s /app/certs/cert-manager/ca.crt /app/certs/ca.crt;
              ln -s /app/certs/cert-manager/ca.key /app/certs/ca.key;
              ln -s /app/certs/cert-manager/admin.crt /app/certs/admin.crt;
              ln -s /app/certs/cert-manager/admin.key /app/certs/admin.key;
              ln -s /app/certs/cert-manager/server.crt /app/certs/server.crt;
              ln -s /app/certs/cert-manager/server.key /app/certs/server.key;
              ln -s /app/certs/cert-manager/token.csv /app/certs/token.csv;
{{- if .Values.api.enableAudit }}
              /app/bin/tke-application-api -C=/app/conf/tke-application-api.toml --audit-policy-file=/app/conf/audit-policy.yaml --audit-webhook-config-file=/app/conf/audit-api-client-config.yaml;
{{- else -}}
              /app/bin/tke-application-api -C=/app/conf/tke-application-api.toml;
{{- end }}
          volumeMounts:
            - name: cert-manager-certs
              mountPath: /app/certs/cert-manager
            - name: cluster-certs
              mountPath: /app/certs/cluster
            - name: certs
              mountPath: /app/certs
            - name: tke-application-api-volume
              mountPath: /app/conf
          ports:
            - containerPort: 9463
          readinessProbe:
            httpGet:
              port: 9463
              path: /healthz/ping
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 9463
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: {{ .Values.api.resources.limits.cpu }}
              memory: {{ .Values.api.resources.limits.memory }}
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
      volumes:
        - name: cluster-certs
          hostPath:
            path: {{ .Values.certificate.mountPath }}
            type: Directory
        - name: cert-manager-certs
          projected:
            sources:
            - secret:
                name: tke-ca
                items:
                - key: tls.crt
                  path: ca.crt
                - key: tls.key
                  path: ca.key
                optional: false
            - secret:
                name: tke-application-server-secret
                items:
                - key: tls.crt
                  path: server.crt
                - key: tls.key
                  path: server.key
                optional: false
            - secret:
                name: tke-ca-admin
                items:
                - key: tls.crt
                  path: admin.crt
                - key: tls.key
                  path: admin.key
                optional: false
            - secret:
                name: tke-application-cluster-secrets
                items:
                - key: token.csv
                  path: token.csv
                optional: false            
        - name: certs
          emptyDir: {}
        - name: tke-application-api-volume
          configMap:
            name: tke-application-api
