kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
{{ toYaml .Values.api.labels | indent 4 }}
  name: tke-notify-api
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.api.annotations }}
  annotations:
{{ toYaml .Values.api.annotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
{{ toYaml .Values.api.selector | indent 4 }}
  template:
    metadata:
      annotations:
        checksum/configmap_config: {{ include (print $.Template.BasePath "/tke-notify-api-configmap.yaml") . | sha256sum }}
      {{- if .Values.api.podAnnotations }}
{{ toYaml .Values.api.podAnnotations | indent 8 }}
      {{- end }}
      labels:
{{ toYaml .Values.api.podLabels | indent 8 }}
    spec:
      affinity:
{{ toYaml .Values.api.affinity | indent 8 }}
    {{- if .Values.api.tolerations }}
      tolerations: {{ toYaml .Values.api.tolerations | nindent 8 }}
    {{- end }}
      containers:
        - name: tke-notify-api
          image: "{{ .Values.notify }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: "{{ .Values.api.image.imagePullPolicy }}"
          command:
            - /bin/sh
            - -c
            - >
              ln -s /app/certs/cluster/etcd/ca.crt /app/certs/etcd-ca.crt;
              ln -s /app/certs/cluster/etcd/ca.crt /app/certs/etcd.crt;
              ln -s /app/certs/cluster/etcd/ca.key /app/certs/etcd.key;
              ln -s /app/certs/cluster/front-proxy-ca.crt /app/certs/front-proxy-ca.crt;
              ln -s /app/certs/cert-manager/ca.crt /app/certs/ca.crt;
              ln -s /app/certs/cert-manager/ca.key /app/certs/ca.key;
              ln -s /app/certs/cert-manager/admin.crt /app/certs/admin.crt;
              ln -s /app/certs/cert-manager/admin.key /app/certs/admin.key;
              ln -s /app/certs/cert-manager/server.crt /app/certs/server.crt;
              ln -s /app/certs/cert-manager/server.key /app/certs/server.key;
              ln -s /app/certs/cert-manager/token.csv /app/certs/token.csv;
{{- if .Values.enableAudit }}
              /app/bin/tke-notify-api -C=/app/conf/tke-notify-api.toml --audit-policy-file=/app/conf/audit-policy.yaml --audit-webhook-config-file=/app/conf/audit-api-client-config.yaml;
{{- else -}}
              /app/bin/tke-notify-api -C=/app/conf/tke-notify-api.toml;
{{- end }}
          volumeMounts:
            - name: cert-manager-certs
              mountPath: /app/certs/cert-manager
            - name: tke-notify-cluster-secrets
              mountPath: /app/certs/cluster
            - name: certs
              mountPath: /app/certs
            - name: tke-notify-api-volume
              mountPath: /app/conf
          ports:
            - containerPort: 9457
          readinessProbe:
            httpGet:
              port: 9457
              path: /healthz/ping
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 9457
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
        {{- if .Values.api.resources }}
          resources: {{ toYaml .Values.api.resources | nindent 12 }}
        {{- end }}

      volumes:
        - name: tke-notify-api-volume
          configMap:
            name: tke-notify-api
        - name: certs
          emptyDir: {}
        - name: tke-notify-cluster-secrets
          hostPath:
            path: {{ .Values.certificate.mountPath }}
            type: Directory
        - name: cert-manager-certs
          projected:
            sources:
              - secret:
                  name: tke-ca
                  items:
                    - key: tls.crt
                      path: ca.crt
                    - key: tls.key
                      path: ca.key
                  optional: false
              - secret:
                  name: tke-notify-server-secret
                  items:
                    - key: tls.crt
                      path: server.crt
                    - key: tls.key
                      path: server.key
                  optional: false
              - secret:
                  name: tke-ca-admin
                  items:
                    - key: tls.crt
                      path: admin.crt
                    - key: tls.key
                      path: admin.key
                  optional: false
              - secret:
                  name: tke-notify-cluster-secrets
                  items:
                    - key: token.csv
                      path: token.csv
                  optional: false
