kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-notify-controller
  namespace: {{ .Release.Namespace | quote }}
data:
  tke-notify-controller.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.notify]
      api_server = "https://tke-notify-api"
      api_server_client_config = "/app/conf/tke-notify-api-config.yaml"

  tke-notify-api-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-notify-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke
