kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
{{ toYaml .Values.controller.labels | indent 4 }}
  name: tke-notify-controller
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.controller.annotations }}
  annotations:
{{ toYaml .Values.controller.annotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
{{ toYaml .Values.controller.selector | indent 4 }}
  template:
    metadata:
      annotations:
        checksum/configmap_config: {{ include (print $.Template.BasePath "/tke-notify-controller-configmap.yaml") . | sha256sum }}
      {{- if .Values.controller.podAnnotations }}
{{ toYaml .Values.controller.podAnnotations | indent 8 }}
      {{- end }}
      labels:
{{ toYaml .Values.controller.podLabels | indent 8 }}
    spec:
      affinity:
{{ toYaml .Values.controller.affinity | indent 8 }}
    {{- if .Values.controller.tolerations }}
      tolerations: {{ toYaml .Values.controller.tolerations | nindent 8 }}
    {{- end }}
      containers:
        - name: tke-notify-controller
          image: "{{ .Values.notify }}/{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: "{{ .Values.controller.image.imagePullPolicy }}"
          command:
            - /bin/sh
            - -c
            - >
              ln -s /app/certs/cert-manager/ca.crt /app/certs/ca.crt;
              ln -s /app/certs/cert-manager/ca.key /app/certs/ca.key;
              ln -s /app/certs/cert-manager/admin.crt /app/certs/admin.crt;
              ln -s /app/certs/cert-manager/admin.key /app/certs/admin.key;
              ln -s /app/certs/cert-manager/server.crt /app/certs/server.crt;
              ln -s /app/certs/cert-manager/server.key /app/certs/server.key;
              /app/bin/tke-notify-controller -C=/app/conf/tke-notify-controller.toml;
          volumeMounts:
            - name: cert-manager-certs
              mountPath: /app/certs/cert-manager
            - name: certs
              mountPath: /app/certs
            - name: tke-notify-controller-volume
              mountPath: /app/conf
          ports:
            - containerPort: 9459
          livenessProbe:
            httpGet:
              port: 9459
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
        {{- if .Values.controller.resources }}
          resources: {{ toYaml .Values.controller.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: tke-notify-controller-volume
          configMap:
            name: tke-notify-controller
        - name: certs
          emptyDir: {}
        - name: cert-manager-certs
          projected:
            sources:
              - secret:
                  name: tke-ca
                  items:
                    - key: tls.crt
                      path: ca.crt
                    - key: tls.key
                      path: ca.key
                  optional: false
              - secret:
                  name: tke-notify-server-secret
                  items:
                    - key: tls.crt
                      path: server.crt
                    - key: tls.key
                      path: server.key
                  optional: false
              - secret:
                  name: tke-ca-admin
                  items:
                    - key: tls.crt
                      path: admin.crt
                    - key: tls.key
                      path: admin.key
                  optional: false
              - secret:
                  name: tke-notify-cluster-secrets
                  items:
                    - key: token.csv
                      path: token.csv
                  optional: false
