apiVersion: v2
appVersion: 1.0.0
dependencies:
- condition: nfd.enabled
  name: node-feature-discovery
  repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  version: 0.8.2
description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
keywords:
- gpu
- cuda
- compute
- operator
- deep learning
- monitoring
- tesla
- addonARCH:amd64
- addonKind:gpu
- owner:addon
kubeVersion: '>= 1.14.0-0'
name: elastic-gpu-operator
version: 1.0.0
