registry: ccr.ccs.tencentyun.com
etcd:
  host: https://etcd.kube-system:2379
provider:
  config: |    
    platformAPIClientConfig: conf/tke-platform-config.yaml
    applicationAPIClientConfig: conf/tke-application-config.yaml
    registry:
      prefix: registry.tke.com/library
      ip: 127.0.0.1
    audit:
      address: ""
    feature:
      skipConditions: []
    docker:
      extraArgs: {}
    kubelet:
      extraArgs: {}
    apiServer:
      extraArgs: {}
    controllerManager:
      extraArgs: {}
    scheduler:
      extraArgs: {}
    authzWebhook:
      endpoint: https://127.0.0.1:31138/auth/authz
    business:
      enabled: true
api:
  labels:
    app: tke-platform-api
  annotations:
  selector:
    matchLabels:
      app: tke-platform-api
  podAnnotations:
  podLabels:
    app: tke-platform-api
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - tke-platform-api
          topologyKey: kubernetes.io/hostname
  replicas: 2
  image:
    repository: tdccimages/tke-platform-api
    tag: industry-cloud-1.9
    imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 150m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  enableAuth: true
  enableAudit: true
  # OIDC认证方式客户端id，默认为default
  oIDCClientID: default
  # OIDC认证方式的issuer_url，默认为https://tke-auth-api/oidc
  oIDCIssuerURL: https://tke-auth-api/oidc
  # 是否开启OIDC认证，默认不开启
  useOIDCCA:
controller:
  labels:
    app: tke-platform-controller
  annotations:
  selector:
    matchLabels:
      app: tke-platform-controller
  podAnnotations:
  podLabels:
    app: tke-platform-controller
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - tke-platform-controller
          topologyKey: kubernetes.io/hostname
  replicas: 2
  providerRes:
    image: 
      repository: tdccimages/provider-res
      tag: v1.21.4-3
      imagePullPolicy: IfNotPresent
  image:
    repository: tdccimages/tke-platform-controller
    tag: industry-cloud-1.9
    imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 128Mi
  registryDomain: ccr.ccs.tencentyun.com
  registryNamespace: tdccimages
certificate:
  serverCertDuration: 876000h
  serverCertRenewBefore: 875900h
  mountPath: /etc/kubernetes/pki
  dnsNames:
  uris: 
  ipAddresses:
kubectl:
  image:
    repository: tdccimages/kubectl
    tag: 1.22.7
    imagePullPolicy: IfNotPresent