apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ toYaml .Values.cilium.operator.labels | indent 4 }}
  name: cilium-operator
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.cilium.operator.annotations }}
  annotations:
{{ toYaml .Values.cilium.operator.annotations | indent 4 }}
  {{- end }}
spec:
  # We support HA mode only for Kubernetes version > 1.14
  # See docs on ServerCapabilities.LeasesResourceLock in file pkg/k8s/version/version.go
  # for more details.
  replicas: 1
  selector:
{{ toYaml .Values.cilium.operator.selector | indent 4 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      {{- if .Values.cilium.operator.podAnnotations }}
      annotations:
{{ toYaml .Values.cilium.operator.podAnnotations | indent 8 }}
      {{- end }}
      labels:
{{ toYaml .Values.cilium.operator.podLabels | indent 8 }}
    spec:
      # In HA mode, cilium-operator pods must not be scheduled on the same
      # node as they will clash with each other.
      affinity:
{{ toYaml .Values.cilium.operator.affinity | indent 8 }}
      containers:
        - args:
            - --config-dir=/tmp/cilium/config-map
            - --debug=$(CILIUM_DEBUG)
          command:
            - cilium-operator-generic
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CILIUM_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CILIUM_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: debug
                  name: cilium-config
                  optional: true
          image: "{{ .Values.registry }}/{{ .Values.cilium.operator.image.repository }}:{{ .Values.cilium.operator.image.tag }}"
          imagePullPolicy: "{{ .Values.cilium.operator.image.imagePullPolicy }}"
          name: cilium-operator
          resources:
            limits:
              cpu: {{ .Values.cilium.operator.resources.limits.cpu }}
              memory: {{ .Values.cilium.operator.resources.limits.memory }}
            requests:
              cpu: {{ .Values.cilium.operator.resources.requests.cpu }}
              memory: {{ .Values.cilium.operator.resources.requests.memory }}
          livenessProbe:
            httpGet:
              host: '127.0.0.1'
              path: /healthz
              port: 9234
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /tmp/cilium/config-map
              name: cilium-config-path
              readOnly: true
      hostNetwork: true
      restartPolicy: Always
      priorityClassName: system-cluster-critical
      serviceAccount: cilium-operator
      serviceAccountName: cilium-operator
      tolerations:
        - operator: Exists
      volumes:
        # To read the configuration from the config map
        - configMap:
            name: cilium-config
          name: cilium-config-path