apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: remote-write
      port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    app: influxdb