{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 10k
    cert-manager.io/issuer: "tke-ca"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  tls:
    - hosts:
        - tke-gateway
        - gateway
        - tke-gateway.tke.svc
        - tke.anywhere
        - registry.tke.com
        - "*.registry.tke.com"
{{- if .Values.certificate.dnsNames }}
{{ toYaml .Values.certificate.dnsNames | indent 8 }}
{{- end }} 
{{- if .Values.certificate.uris }}
{{ toYaml .Values.certificate.uris | indent 8 }}
{{- end }}
        - 127.0.0.1
{{- if .Values.certificate.ipAddresses }}
{{ toYaml .Values.certificate.ipAddresses | indent 8 }}
{{- end }}
      secretName: tke-gateway-server-secret
  rules:
    - host: "registry.tke.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tke-gateway
                port:
                  number: 80
    - host: "*.registry.tke.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tke-gateway
                port:
                  number: 80
    - host: "tke-gateway"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tke-gateway
                port:
                  number: 80
    - host: "tke.anywhere"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tke-gateway
                port:
                  number: 80
{{- range .Values.certificate.dnsNames }}
    - host: {{ . }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tke-gateway
                port:
                  number: 80
{{- end }}
{{- with .Values.ingress.rules }}
{{ toYaml . | indent 4 }}
{{- end }}
  ingressClassName: nginx
{{- end -}}