apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- if .Values.labels }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  {{- end }}
  name: keepalived
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
  {{- end }}
spec:
  selector:
{{ toYaml .Values.selector | indent 4 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
      labels:
{{ toYaml .Values.podLabels | indent 8 }}
    spec:
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: "NoSchedule"
      containers:
        - image: "{{ .Values.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
          name: keepalived
          args:
            - --log-console
            - --dont-fork
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /etc/keepalived/
              name: conf-volume
      hostNetwork: true
      volumes:
        - configMap:
            name: keepalived-config
          name: conf-volume
